version: "2.4"

services:
  mysql:
    image: mysql:5.7.41-oracle
    environment:
      MYSQL_USER: &MYSQL_USER projectino
      MYSQL_HOST: &MYSQL_HOST mysql 
      MYSQL_PASSWORD: &MYSQL_PASSWORD 'pass'
      MYSQL_DATABASE: &MYSQL_DATABASE projectino
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  redmine:
    image: redmine
    depends_on:
      database-setup:
        condition: service_completed_successfully
    environment:
      REDMINE_DB_MYSQL: *MYSQL_HOST
      REDMINE_DB_USERNAME: *MYSQL_USER 
      REDMINE_DB_PASSWORD: *MYSQL_PASSWORD
      REDMINE_DB_DATABASE: *MYSQL_DATABASE
    ports:
      - "3001:3000"


  database-setup:
    pull_policy: build
    build: database-setup
    environment:
      MYSQL_USER: *MYSQL_USER
      MYSQL_HOST: *MYSQL_HOST 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    depends_on: 
      - mysql
